// The `grid:` block is this pack's SINGLE authored asset declaration. Pins: the
// closed selector grammar and its grid_sdk mapping, the refusals (each naming
// the asset and the field), the ATOMIC two-output write, `--check` staleness,
// and the committed outputs being a fresh render of the committed block.
// Offline; the block reader is exercised through an injected Fake path probe.
import 'dart:convert';
import 'dart:io';

import 'package:grid_assets/grid_assets.dart';
import 'package:grid_sdk/grid_sdk.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../support/package_root.dart';

/// A Fake artifact probe: exactly [present] resolves, nothing else does.
class FakePathProbe {
  FakePathProbe(this.present);

  final Set<String> present;

  bool call(String path) => present.contains(path);
}

const String _skillPath = 'extension/x/SKILL.md';

/// The language version every fixture package here is authored against, and
/// therefore the one the generator must format its Dart at — matched by the
/// oracle helpers below.
const String _fixtureLanguageVersion = '3.11';

/// A fixture pubspec. [sdk] is the `environment.sdk` constraint; passing
/// `null` OMITS the whole `environment:` map, the shape the generator refuses.
String _pubspec(String assets, {String? sdk = '^$_fixtureLanguageVersion.0'}) =>
    'name: grid_assets\n'
    '${sdk == null ? '' : 'environment:\n  sdk: "$sdk"\n'}'
    'grid:\n'
    '  assets:\n$assets'
    '  station_overlay:\n'
    '    mappings:\n'
    '      claude: .claude\n';

/// A description long enough that `description: '<it>'` cannot fit on one
/// line — the exact shape whose wrapping drifted between the SDK formatter and
/// a workspace-resolved `dart_style`.
const String _longDescription =
    'A probe whose description runs deliberately past eighty columns, so the '
    'generated argument cannot fit on a single line under any formatter.';

String _skill({
  String? selector,
  String audience = 'agent',
  List<String>? teaches,
  String description = 'A probe.',
}) =>
    '    - id: probe\n'
    '      kind: skill\n'
    '      description: "$description"\n'
    '      audience: $audience\n'
    '      visibility: public\n'
    '${selector == null ? '' : '      selector: "$selector"\n'}'
    '${teaches == null ? '' : '      teaches: [${teaches.join(', ')}]\n'}'
    '      artifacts:\n'
    '        - target: claude\n'
    '          path: $_skillPath\n';

GridBlock _parse(String assets) => parseGridBlock(
  pubspecYaml: _pubspec(assets),
  pathExists: FakePathProbe({_skillPath}).call,
);

/// The real package root — also the formatter's working directory, so the
/// oracle and the generator ask from the same place.
final String _root = packageRoot();

/// The INDEPENDENT oracle: the RUNNING SDK's own `dart format`, spawned here
/// as its own process, answering what bytes it would leave for [file].
///
/// Deliberately NOT the generator's own call and NOT a `dart_style` API, and
/// deliberately [Platform.resolvedExecutable] rather than a bare `dart` off
/// `PATH` — the claim under test is that generated bytes agree with the
/// formatter of the SDK the generator itself runs under, asked at the
/// PACKAGE's language version, which is the version the lane's gate reads out
/// of the pubspec.
String _sdkFormatted(File file) {
  final result = Process.runSync(
    Platform.resolvedExecutable,
    [
      'format',
      '--output=show',
      '--show=none',
      '--summary=none',
      '--language-version=$_fixtureLanguageVersion',
      file.path,
    ],
    workingDirectory: _root,
    stdoutEncoding: utf8,
    stderrEncoding: utf8,
  );
  expect(result.exitCode, 0, reason: '${result.stderr}');
  return result.stdout as String;
}

/// The lane's own question — `dart format --set-exit-if-changed` over [file],
/// asked of the same running SDK.
int _sdkFormatCleanExit(File file) =>
    Process.runSync(Platform.resolvedExecutable, [
      'format',
      '--output=none',
      '--set-exit-if-changed',
      '--language-version=$_fixtureLanguageVersion',
      file.path,
    ], workingDirectory: _root).exitCode;

/// One observed `dart format` invocation.
class _FakeProcessCall {
  _FakeProcessCall({
    required this.executable,
    required this.arguments,
    required this.workingDirectory,
    required this.stdoutEncoding,
    required this.stderrEncoding,
  });

  final String executable;
  final List<String> arguments;
  final String? workingDirectory;
  final Encoding? stdoutEncoding;
  final Encoding? stderrEncoding;
}

/// A Fake synchronous process runner, substituted for `Process.runSync` at the
/// generator's formatter seam.
///
/// Records every invocation and answers with the scratch file's own bytes as
/// successful stdout, so the argv the generator would hand `dart format` is
/// observable WITHOUT spawning a Dart — which is the only way to see the
/// requested language version at all, the formatter itself being byte-silent
/// about which version it applied.
class _FakeFormatProcessRunner {
  final List<_FakeProcessCall> calls = <_FakeProcessCall>[];

  ProcessResult call(
    String executable,
    List<String> arguments, {
    String? workingDirectory,
    Encoding? stdoutEncoding,
    Encoding? stderrEncoding,
  }) {
    calls.add(
      _FakeProcessCall(
        executable: executable,
        arguments: List<String>.unmodifiable(arguments),
        workingDirectory: workingDirectory,
        stdoutEncoding: stdoutEncoding,
        stderrEncoding: stderrEncoding,
      ),
    );
    return ProcessResult(0, 0, File(arguments.last).readAsStringSync(), '');
  }
}

void main() {
  group('the selector grammar is CLOSED and maps onto grid_sdk', () {
    test('omission means unknown and renders EXACTLY as `any` does', () {
      final omitted = _parse(_skill());
      final declared = _parse(_skill(selector: 'any'));
      expect(omitted.assets.single.selector, isA<AlwaysApplies>());
      expect(declared.assets.single.selector, isA<AlwaysApplies>());
      expect(
        selectorExpression(omitted.assets.single.selector),
        selectorExpression(declared.assets.single.selector),
      );
      expect(omitted.undeclaredSelectorAssetIds, ['grid_assets/skill/probe']);
      expect(declared.undeclaredSelectorAssetIds, isEmpty);
    });

    test('`unknown` is spellable and identical to omission', () {
      expect(
        _parse(_skill(selector: 'unknown')).assets.single.selector,
        isA<AlwaysApplies>(),
      );
    });

    test(
      'the parameterised and path tokens map to their grid_sdk variants',
      () {
        expect(
          _parse(
            _skill(selector: 'dart-package:grid_sdk'),
          ).assets.single.selector,
          isA<RequiresPackage>().having(
            (s) => s.packageName,
            'packageName',
            'grid_sdk',
          ),
        );
        expect(
          _parse(_skill(selector: 'decision-register')).assets.single.selector,
          isA<RequiresPath>().having(
            (s) => s.relativePath,
            'relativePath',
            'docs/decisions',
          ),
        );
        expect(
          _parse(_skill(selector: 'station')).assets.single.selector,
          isA<RequiresPath>().having(
            (s) => s.relativePath,
            'relativePath',
            '.grid',
          ),
        );
      },
    );

    test('`never` is refused LOUD, naming the absent grid_sdk variant', () {
      expect(
        () => _parse(_skill(selector: 'never')),
        throwsA(
          isA<GridBlockException>().having(
            (e) => e.message,
            'message',
            allOf(
              contains('asset "skill/probe"'),
              contains('selector:'),
              contains('no unsatisfiable variant'),
            ),
          ),
        ),
      );
    });

    test('an unrecognised token and a stray argument are both refused', () {
      expect(
        () => _parse(_skill(selector: 'sometimes')),
        throwsA(
          isA<GridBlockException>().having(
            (e) => e.message,
            'message',
            contains('unrecognised selector "sometimes"'),
          ),
        ),
      );
      expect(
        () => _parse(_skill(selector: 'station:extra')),
        throwsA(
          isA<GridBlockException>().having(
            (e) => e.message,
            'message',
            contains('"station" takes no argument'),
          ),
        ),
      );
      expect(
        () => _parse(_skill(selector: 'dart-package:')),
        throwsA(
          isA<GridBlockException>().having(
            (e) => e.message,
            'message',
            contains('requires a package name'),
          ),
        ),
      );
    });
  });

  group('the teaches claim couples a skill to the commands it teaches', () {
    test('a skill teaches commands in declaration order', () {
      expect(
        _parse(
          _skill(teaches: ['filing', 'approve', 'link']),
        ).assets.single.teaches,
        ['filing', 'approve', 'link'],
      );
      expect(_parse(_skill()).assets.single.teaches, isEmpty);
      expect(_parse(_skill(teaches: [])).assets.single.teaches, isEmpty);
    });

    test('malformed teaches declarations are refused with exact fields', () {
      void refuses(String assets, String field) => expect(
        () => _parse(assets),
        throwsA(
          isA<GridBlockException>().having(
            (e) => e.message,
            'message',
            startsWith(field),
          ),
        ),
      );

      // A bare scalar is not a claim — the value must be a list.
      refuses(
        '    - id: probe\n'
            '      kind: skill\n'
            '      description: "A probe."\n'
            '      teaches: filing\n'
            '      artifacts:\n'
            '        - target: claude\n'
            '          path: $_skillPath\n',
        'grid: asset "skill/probe": teaches: must be a list',
      );
      // Only a skill teaches; every other kind may claim nothing.
      refuses(
        '    - id: probe\n'
            '      kind: prompt\n'
            '      description: "A probe."\n'
            '      teaches: [filing]\n'
            '      artifacts:\n'
            '        - target: claude\n'
            '          path: $_skillPath\n',
        'grid: asset "prompt/probe": teaches: may be non-empty only for '
            'kind "skill"',
      );
      const String entryReason =
          'must be one lowercase top-level command name matching '
          r'^[a-z][a-z0-9-]*$';
      refuses(
        '    - id: probe\n'
            '      kind: skill\n'
            '      description: "A probe."\n'
            '      teaches: ["", filing]\n'
            '      artifacts:\n'
            '        - target: claude\n'
            '          path: $_skillPath\n',
        'grid: asset "skill/probe": teaches[0]: $entryReason',
      );
      refuses(
        _skill(teaches: ['Filing']),
        'grid: asset "skill/probe": teaches[0]: $entryReason',
      );
      refuses(
        _skill(teaches: ['filing', 'filing']),
        'grid: asset "skill/probe": teaches[1]: duplicate command "filing"',
      );
    });

    test('Dart emission carries teaches and MCP emission omits it', () {
      final claimed = _parse(_skill(teaches: ['filing', 'approve']));
      final source = renderGridAssetPackLibrary(claimed);
      expect(source, contains("teaches: <String>['filing', 'approve'],"));
      expect(
        source.indexOf('teaches:'),
        allOf(
          greaterThan(source.indexOf('selector:')),
          lessThan(source.indexOf('artifacts:')),
        ),
      );
      expect(
        renderGridAssetPackLibrary(_parse(_skill())),
        isNot(contains('teaches')),
      );
      expect(
        renderGridAssetPackLibrary(_parse(_skill(teaches: []))),
        isNot(contains('teaches')),
      );
      // The MCP mirror is compatibility output, never a second authority.
      expect(renderMcpConfig(claimed), isNot(contains('teaches')));
    });
  });

  group('every malformed field is refused, naming the asset and the field', () {
    void refuses(String assets, Matcher message) => expect(
      () => _parse(assets),
      throwsA(
        isA<GridBlockException>().having((e) => e.message, 'message', message),
      ),
    );

    test('an unrecognised kind', () {
      refuses(
        '    - id: probe\n'
        '      kind: widget\n'
        '      description: "A probe."\n'
        '      artifacts:\n'
        '        - target: claude\n'
        '          path: $_skillPath\n',
        allOf(
          contains('unknown/probe'),
          contains('unrecognised kind "widget"'),
        ),
      );
    });

    test('an unrecognised audience and an unrecognised visibility', () {
      refuses(
        _skill(audience: 'robot'),
        allOf(
          contains('asset "skill/probe"'),
          contains('unrecognised audience "robot"'),
        ),
      );
      refuses(
        '    - id: probe\n'
        '      kind: skill\n'
        '      description: "A probe."\n'
        '      visibility: secret\n'
        '      artifacts:\n'
        '        - target: claude\n'
        '          path: $_skillPath\n',
        contains('unrecognised visibility "secret"'),
      );
    });

    test('an unrecognised delivery target', () {
      refuses(
        '    - id: probe\n'
        '      kind: skill\n'
        '      description: "A probe."\n'
        '      artifacts:\n'
        '        - target: emacs\n'
        '          path: $_skillPath\n',
        allOf(
          contains('artifacts[0].target'),
          contains('unrecognised target "emacs"'),
        ),
      );
    });

    test('a path that does not exist', () {
      refuses(
        '    - id: probe\n'
        '      kind: skill\n'
        '      description: "A probe."\n'
        '      artifacts:\n'
        '        - target: claude\n'
        '          path: extension/nope/SKILL.md\n',
        allOf(
          contains('artifacts[0].path'),
          contains('"extension/nope/SKILL.md" does not exist'),
        ),
      );
    });

    test('a duplicate logical identity', () {
      refuses(
        _skill() + _skill(),
        allOf(
          contains('asset "skill/probe"'),
          contains('duplicate logical identity'),
        ),
      );
    });

    test('a duplicate delivery target within ONE asset', () {
      refuses(
        '    - id: probe\n'
        '      kind: skill\n'
        '      description: "A probe."\n'
        '      artifacts:\n'
        '        - target: claude\n'
        '          path: $_skillPath\n'
        '        - target: claude\n'
        '          path: $_skillPath\n',
        allOf(
          contains('artifacts[1].target'),
          contains('duplicate delivery target "claude"'),
        ),
      );
    });
  });

  group('the MCP mirror carries only MCP concepts', () {
    test('human renders as operator, extension/ is stripped, and agent- and '
        'settings-kind assets are NOT mirrored', () {
      final block = parseGridBlock(
        pubspecYaml: _pubspec(
          '${_skill(audience: 'human')}'
          '    - id: governor\n'
          '      kind: agent\n'
          '      description: "The seat."\n'
          '      audience: human\n'
          '      artifacts:\n'
          '        - target: claude\n'
          '          path: $_skillPath\n',
        ),
        pathExists: FakePathProbe({_skillPath}).call,
      );
      final yaml = renderMcpConfig(block);
      expect(yaml, contains(kGridBlockGeneratedMarker));
      expect(yaml, contains('audience: operator'));
      expect(yaml, contains('path: x/SKILL.md'));
      expect(yaml, isNot(contains('id: governor')));
      expect(yaml, isNot(contains('kind:')));
      expect(yaml, isNot(contains('selector:')));
    });
  });

  group('the committed outputs ARE a fresh render of the committed block', () {
    final root = _root;

    test('the generator reports current (--check exits 0)', () {
      final out = StringBuffer();
      // Typed ON PURPOSE: every pack's tool wrapper assigns this straight to
      // `exitCode`, so the API must stay a synchronous `int`.
      final int exit = runGridAssetsGenerator(
        packageRoot: root,
        check: true,
        out: out,
      );
      expect(exit, 0, reason: out.toString());
      expect(out.toString(), contains('UNDECLARED selector'));
    });

    // The regression that is detectable WITHOUT a drifted workspace: the
    // normalizer must shell the RUNNING SDK, never a formatter the consuming
    // workspace resolved — that package's style may sit ahead of the SDK
    // formatter the format-clean lane actually runs.
    test(
      'the generator invokes the running SDK and no workspace formatter',
      () {
        final source = File(
          p.join(root, 'lib', 'src', 'assets', 'grid_block.dart'),
        ).readAsStringSync();
        // Whitespace-collapsed: `dart format` wraps the injected seam's
        // structural type across lines, and the claim is the DEFAULT, not the
        // wrapping.
        expect(
          source.replaceAll(RegExp(r'\s+'), ' '),
          contains('runProcess = Process.runSync,'),
          reason: 'the process seam defaults to the real one',
        );
        for (final fragment in const [
          'Platform.resolvedExecutable',
          '--output=show',
          'workingDirectory: packageRoot',
          'stdoutEncoding: utf8',
        ]) {
          expect(source, contains(fragment), reason: 'the SDK formatter call');
        }
        expect(source, isNot(contains('package:dart_style/dart_style.dart')));
        expect(source, isNot(contains('DartFormatService')));
        // The whole defect: `latest` made the rendered bytes a function of the
        // SDK that happened to run the generator.
        expect(source, isNot(contains('--language-version=latest')));
      },
    );

    test('the real block declares 33 assets across five kinds', () {
      final block = parseGridBlock(
        pubspecYaml: File(p.join(root, 'pubspec.yaml')).readAsStringSync(),
        pathExists: (relative) =>
            File(p.join(root, relative)).existsSync() ||
            Directory(p.join(root, relative)).existsSync(),
      );
      expect(block.assets, hasLength(33));
      expect(block.assets.map((a) => a.assetKey.kind).toSet(), {
        AssetKind.rubric,
        AssetKind.prompt,
        AssetKind.skill,
        AssetKind.agent,
        AssetKind.settings,
      });
      expect(block.stationOverlayMappings, {'claude': '.claude'});
    });

    test('audience and selector are honoured INDEPENDENTLY', () {
      final assetAuthor = GridAssetsPack.assets.firstWhere(
        (a) => a.assetKey.id == 'asset-author',
      );
      expect(assetAuthor.audience, AssetAudience.human);
      expect(
        assetAuthor.selector,
        isA<RequiresPackage>().having(
          (s) => s.packageName,
          'packageName',
          'grid_sdk',
        ),
      );
      final decisionAlignment = GridAssetsPack.assets.firstWhere(
        (a) => a.assetKey.id == 'decision-alignment',
      );
      expect(decisionAlignment.audience, AssetAudience.agent);
      expect(
        decisionAlignment.selector,
        isA<RequiresPath>().having(
          (s) => s.relativePath,
          'relativePath',
          'docs/decisions',
        ),
      );
    });

    test('the real pack carries exactly the five baseline teaches claims', () {
      expect(
        <String, List<String>>{
          for (final asset in GridAssetsPack.assets)
            if (asset.teaches.isNotEmpty) asset.assetKey.id: asset.teaches,
        },
        {
          'asset-author': ['assets'],
          'discover': ['search'],
          'handoff': ['succession'],
          'intake-refinement': ['filing', 'approve', 'link'],
          'station-operations': ['up', 'down', 'status'],
        },
      );
    });

    test('the pack validates and both legs of every skill are keyed', () {
      expect(GridAssetsPack.definition.assets, hasLength(33));
      final discover = GridAssetsPack.assets.firstWhere(
        (a) => a.assetKey.id == 'discover',
      );
      expect(discover.artifactKeys.map((k) => k.canonical), [
        'grid_assets/skill/discover@claude',
        'grid_assets/skill/discover@agents',
      ]);
      // A seat role definition is CLAUDE-ONLY: each harness leg is an
      // independent instruction source, and no leg but claude reads a role
      // definition today
      // (`power_station#a-harness-may-carry-its-own-instructions`).
      final refiner = GridAssetsPack.assets.firstWhere(
        (a) => a.assetKey.id == 'refiner',
      );
      expect(refiner.artifactKeys.map((k) => k.canonical), [
        'grid_assets/agent/refiner@claude',
      ]);
    });
  });

  group('emission is ATOMIC and --check is honest', () {
    late Directory temp;

    setUp(() {
      temp = Directory.systemTemp.createTempSync('grid-block-');
      final source = _root;
      for (final relative in const [
        kGeneratedPackPath,
        kGeneratedMcpPath,
        _skillPath,
      ]) {
        final target = File(p.join(temp.path, relative));
        target.parent.createSync(recursive: true);
        if (relative == _skillPath) {
          target.writeAsStringSync('body\n');
        } else {
          target.writeAsStringSync(
            File(p.join(source, relative)).readAsStringSync(),
          );
        }
      }
    });

    tearDown(() => temp.deleteSync(recursive: true));

    void writePubspec(String assets) => File(
      p.join(temp.path, 'pubspec.yaml'),
    ).writeAsStringSync(_pubspec(assets));

    test('a malformed block leaves BOTH outputs byte-unchanged', () {
      final before = <String, String>{
        for (final relative in const [kGeneratedPackPath, kGeneratedMcpPath])
          relative: File(p.join(temp.path, relative)).readAsStringSync(),
      };
      writePubspec(
        '    - id: probe\n'
        '      kind: widget\n'
        '      description: "A probe."\n'
        '      artifacts:\n'
        '        - target: claude\n'
        '          path: $_skillPath\n',
      );
      expect(
        () =>
            runGridAssetsGenerator(packageRoot: temp.path, out: StringBuffer()),
        throwsA(isA<GridBlockException>()),
      );
      before.forEach((relative, text) {
        expect(File(p.join(temp.path, relative)).readAsStringSync(), text);
      });
    });

    test(
      '--check exits non-zero and names the stale path, writing nothing',
      () {
        writePubspec(_skill());
        final out = StringBuffer();
        expect(
          runGridAssetsGenerator(packageRoot: temp.path, check: true, out: out),
          isNot(0),
        );
        expect(out.toString(), contains('STALE $kGeneratedPackPath'));
        expect(out.toString(), contains('STALE $kGeneratedMcpPath'));
        expect(
          File(p.join(temp.path, kGeneratedPackPath)).readAsStringSync(),
          contains('code-validation'),
          reason: '--check writes nothing',
        );
      },
    );

    test(
      'a write formats Dart only, makes --check clean, and re-running is a no-op',
      () {
        writePubspec(_skill());
        expect(
          runGridAssetsGenerator(packageRoot: temp.path, out: StringBuffer()),
          0,
        );

        final dartFile = File(p.join(temp.path, kGeneratedPackPath));
        final mcpFile = File(p.join(temp.path, kGeneratedMcpPath));
        final generatedDart = dartFile.readAsStringSync();
        final generatedMcp = mcpFile.readAsStringSync();
        expect(generatedDart, contains(kGridBlockGeneratedMarker));
        expect(
          _sdkFormatted(dartFile),
          generatedDart,
          reason: 'the generator writes SDK-formatter-normalized Dart',
        );
        expect(
          generatedMcp,
          renderMcpConfig(_parse(_skill())),
          reason: 'non-Dart outputs remain the pure renderer bytes',
        );
        expect(
          runGridAssetsGenerator(
            packageRoot: temp.path,
            check: true,
            out: StringBuffer(),
          ),
          0,
        );

        expect(
          runGridAssetsGenerator(packageRoot: temp.path, out: StringBuffer()),
          0,
        );
        expect(dartFile.readAsStringSync(), generatedDart);
        expect(mcpFile.readAsStringSync(), generatedMcp);
      },
    );

    // The DEFECT this pins: the generator used to normalize with whatever
    // `dart_style` the CONSUMING workspace resolved. One minor ahead of the
    // SDK's bundled formatter, that package kept a long `description:`
    // argument on one line where the SDK split it — so a freshly regenerated
    // pack passed `--check` and still failed the station's format-clean lane.
    test('SDK formatter owns generated Dart for a description longer than '
        '80 characters', () {
      expect(_longDescription.length, greaterThan(80));
      writePubspec(_skill(description: _longDescription));
      expect(
        runGridAssetsGenerator(packageRoot: temp.path, out: StringBuffer()),
        0,
      );

      final dartFile = File(p.join(temp.path, kGeneratedPackPath));
      final generatedDart = dartFile.readAsStringSync();
      expect(generatedDart, contains(_longDescription));
      expect(
        _sdkFormatted(dartFile),
        generatedDart,
        reason:
            'the SDK formatter — not a resolved dart_style — owns the '
            'wrapping of a long description argument',
      );
    });

    test('SDK-formatted long-description output is current and '
        'format-clean', () {
      writePubspec(_skill(description: _longDescription));
      expect(
        runGridAssetsGenerator(packageRoot: temp.path, out: StringBuffer()),
        0,
      );

      final dartFile = File(p.join(temp.path, kGeneratedPackPath));
      final mcpFile = File(p.join(temp.path, kGeneratedMcpPath));
      final generatedDart = dartFile.readAsStringSync();
      final generatedMcp = mcpFile.readAsStringSync();

      expect(
        runGridAssetsGenerator(
          packageRoot: temp.path,
          check: true,
          out: StringBuffer(),
        ),
        0,
        reason: 'a fresh render of an unchanged block is never STALE',
      );
      expect(
        _sdkFormatCleanExit(dartFile),
        0,
        reason: 'dart format --set-exit-if-changed accepts the written bytes',
      );
      expect(dartFile.readAsStringSync(), generatedDart);
      expect(mcpFile.readAsStringSync(), generatedMcp);
    });
  });

  // The DEFECT this pins: the generator formatted at `--language-version=
  // latest`, so the rendered bytes were a function of whichever SDK ran it. The
  // SAME commit that was current under Dart 3.12 read STALE under 3.13, and no
  // single committed registry could satisfy `dart format --set-exit-if-changed`
  // on both. The language version the CONSUMING package declares is the one the
  // lane's gate reads, so it is the one the generator must render at.
  group('generated Dart is formatted at the PACKAGE language version', () {
    late Directory temp;
    late _FakeFormatProcessRunner runner;

    setUp(() {
      temp = Directory.systemTemp.createTempSync('grid-block-language-');
      runner = _FakeFormatProcessRunner();
      File(p.join(temp.path, _skillPath))
        ..parent.createSync(recursive: true)
        ..writeAsStringSync('body\n');
      for (final relative in const [kGeneratedPackPath, kGeneratedMcpPath]) {
        File(p.join(temp.path, relative)).parent.createSync(recursive: true);
      }
    });

    tearDown(() => temp.deleteSync(recursive: true));

    void writePubspec({String? sdk}) => File(
      p.join(temp.path, 'pubspec.yaml'),
    ).writeAsStringSync(_pubspec(_skill(), sdk: sdk));

    /// Generates against the fixture through the Fake, and answers the ONE
    /// formatter call it made — the YAML mirror never reaches a formatter.
    _FakeProcessCall generate() {
      expect(
        runGridAssetsGenerator(
          packageRoot: temp.path,
          out: StringBuffer(),
          runProcess: runner.call,
        ),
        0,
      );
      expect(
        runner.calls,
        hasLength(1),
        reason: 'Dart only, and no Dart process was spawned',
      );
      return runner.calls.single;
    }

    test('caret SDK constraint drives dart format language version', () {
      writePubspec(sdk: '^3.9.0');
      final call = generate();
      expect(call.arguments, contains('--language-version=3.9'));
      expect(call.arguments, isNot(contains('--language-version=latest')));
      expect(call.executable, Platform.resolvedExecutable);
      expect(call.arguments.first, 'format');
      expect(
        p.basename(call.arguments.last),
        p.basename(kGeneratedPackPath),
        reason: 'the formatter reads a scratch copy of the generated pack',
      );
      expect(
        p.isWithin(temp.path, call.arguments.last),
        isFalse,
        reason: 'the scratch copy lives outside the package the caller owns',
      );
      expect(call.workingDirectory, temp.path);
      expect(call.stdoutEncoding, utf8);
      expect(call.stderrEncoding, utf8);
    });

    test('bounded SDK constraint drives dart format language version', () {
      writePubspec(sdk: '>=3.10.0 <4.0.0');
      expect(
        generate().arguments,
        contains('--language-version=3.10'),
        reason: 'the INCLUSIVE floor, not the upper bound',
      );
    });

    test('missing environment.sdk refuses before formatter invocation', () {
      writePubspec();
      expect(
        () => runGridAssetsGenerator(
          packageRoot: temp.path,
          out: StringBuffer(),
          runProcess: runner.call,
        ),
        throwsA(
          isA<GridBlockException>().having(
            (e) => e.message,
            'message',
            allOf(
              startsWith('grid: "grid_assets": environment.sdk:'),
              contains('`environment:` map'),
            ),
          ),
        ),
      );
      expect(runner.calls, isEmpty, reason: 'refused before it could format');
      expect(
        File(p.join(temp.path, kGeneratedPackPath)).existsSync(),
        isFalse,
        reason: 'and before either output was written',
      );
    });
  });
}
