/// The `grid:` block — this package's SINGLE authored asset declaration — and
/// the generator that renders it into the two committed outputs.
///
/// A package participates in the station's compiled asset registry exactly when
/// its pubspec carries a top-level `grid:` block
/// (`the_grid#grid-block-packages-publish-dart-asset-definitions`). This library
/// READS that block and RENDERS `grid_sdk` values; it declares no registry type
/// of its own, and it evaluates no selector — a selector is DECLARED here and
/// resolved above, by a later resolver holding substation facts.
library;

import 'package:grid_sdk/grid_sdk.dart';
import 'package:yaml/yaml.dart';

/// The marker BOTH generated outputs carry, so a reader tells a generated file
/// from a hand-authored one.
///
/// Deliberately NOT the overlay provenance stamp: that one is the overlay
/// materializer's and embeds the checkout's source ref, which would churn both
/// outputs on every commit and make `--check` fail against an unchanged block.
const String kGridBlockGeneratedMarker =
    'GENERATED by tool/generate_grid_assets.dart';

/// Where the `decision-register` selector points.
const String kDecisionRegisterPath = 'docs/decisions';

/// Where the `station` selector points — the grid's own state store.
const String kStationStorePath = '.grid';

/// The closed selector grammar, rendered for a refusal message.
const String kSelectorGrammar =
    'any, dart-package:<name>, decision-register, station, never, '
    'or omit for unknown';

/// A LOUD refusal from the `grid:` block reader.
///
/// Guards LOUD or GONE (the D-H doctrine, ADR-0008): a malformed block never
/// degrades to a partial pack, and every message names the asset and the field.
final class GridBlockException implements Exception {
  /// Refuses with [message].
  const GridBlockException(this.message);

  /// The refusal, naming the asset and the field.
  final String message;

  @override
  String toString() => message;
}

Never _refuse(String asset, String field, String reason) =>
    throw GridBlockException('grid: asset "$asset": $field: $reason');

/// Answers whether a package-relative artifact path exists.
typedef ArtifactPathProbe = bool Function(String packageRelativePath);

/// One parsed, validated `grid:` block.
final class GridBlock {
  /// Holds the block's [package], its [assets] in declaration order, its
  /// [stationOverlayMappings], and [undeclaredSelectorAssetIds].
  const GridBlock({
    required this.package,
    required this.assets,
    required this.stationOverlayMappings,
    required this.undeclaredSelectorAssetIds,
  });

  /// The vending Dart package.
  final String package;

  /// The declared assets, in declaration order.
  final List<GridAssetDefinition> assets;

  /// The overlay head → target mappings this pack declares.
  final Map<String, String> stationOverlayMappings;

  /// The canonical keys of assets whose block OMITTED `selector`.
  ///
  /// They resolve exactly as `any` does, and stay reportable as UNDECLARED.
  final List<String> undeclaredSelectorAssetIds;
}

/// Parses the `grid:` block out of [pubspecYaml], refusing LOUD on any
/// malformed field, missing artifact path, duplicate [AssetKey], or duplicate
/// [AssetArtifactKey].
///
/// [pathExists] answers whether a package-relative artifact path resolves; it
/// is injected so the block reader stays pure (a Fake in test, `dart:io` in the
/// generator).
GridBlock parseGridBlock({
  required String pubspecYaml,
  required ArtifactPathProbe pathExists,
}) {
  final doc = loadYaml(pubspecYaml);
  if (doc is! YamlMap) {
    throw const GridBlockException('grid: the pubspec is not a YAML map');
  }
  final name = doc['name'];
  if (name is! String || name.trim().isEmpty) {
    throw const GridBlockException(
      'grid: the pubspec declares no package name',
    );
  }
  final block = doc['grid'];
  if (block is! YamlMap) {
    throw GridBlockException(
      'grid: "$name" carries no top-level `grid:` block',
    );
  }
  final rawAssets = block['assets'];
  if (rawAssets is! YamlList) {
    throw GridBlockException('grid: "$name": assets: must be a list');
  }

  final assets = <GridAssetDefinition>[];
  final undeclared = <String>[];
  final seenAssets = <String>{};
  for (final raw in rawAssets) {
    if (raw is! YamlMap) {
      throw GridBlockException('grid: "$name": assets: every entry is a map');
    }
    final id = raw['id'];
    if (id is! String || id.trim().isEmpty) {
      throw GridBlockException('grid: "$name": assets: an entry declares no id');
    }
    final kind = _kind(raw['kind'], id);
    final label = '${kind.name}/$id';
    if (!seenAssets.add(label)) {
      _refuse(label, 'id', 'duplicate logical identity — already declared');
    }
    if (raw['selector'] == null) undeclared.add('$name/$label');
    assets.add(
      GridAssetDefinition(
        assetKey: AssetKey(package: name, kind: kind, id: id),
        description: _text(raw, 'description', label),
        audience: _audience(raw['audience'], label),
        visibility: _visibility(raw['visibility'], label),
        selector: parseAssetSelector(raw['selector'], label),
        artifacts: _artifacts(raw['artifacts'], label, pathExists),
      ),
    );
  }
  return GridBlock(
    package: name,
    assets: List<GridAssetDefinition>.unmodifiable(assets),
    stationOverlayMappings: _mappings(block['station_overlay'], name),
    undeclaredSelectorAssetIds: List<String>.unmodifiable(undeclared),
  );
}

String _text(YamlMap raw, String field, String label) {
  final value = raw[field];
  if (value is! String || value.trim().isEmpty) {
    _refuse(label, field, 'must be a non-empty string');
  }
  return value.trim();
}

AssetKind _kind(Object? raw, String id) {
  for (final kind in AssetKind.values) {
    if (kind.name == raw) return kind;
  }
  _refuse(
    'unknown/$id',
    'kind',
    'unrecognised kind "$raw" (expected one of '
        '${AssetKind.values.map((k) => k.name).join(', ')})',
  );
}

AssetAudience _audience(Object? raw, String label) {
  if (raw == null) return AssetAudience.agent;
  for (final audience in AssetAudience.values) {
    if (audience.name == raw) return audience;
  }
  _refuse(
    label,
    'audience',
    'unrecognised audience "$raw" (expected one of '
        '${AssetAudience.values.map((a) => a.name).join(', ')})',
  );
}

AssetVisibility _visibility(Object? raw, String label) {
  if (raw == null) return AssetVisibility.public;
  for (final visibility in AssetVisibility.values) {
    if (visibility.name == raw) return visibility;
  }
  _refuse(
    label,
    'visibility',
    'unrecognised visibility "$raw" (expected one of '
        '${AssetVisibility.values.map((v) => v.name).join(', ')})',
  );
}

/// Maps one CLOSED selector token onto the `grid_sdk` [AssetSelector] union.
///
/// `null` (omitted), `unknown`, and `any` all yield [AlwaysApplies]; the
/// omission is separately reported through
/// [GridBlock.undeclaredSelectorAssetIds]. `never` is grammar-valid and
/// REFUSED: `grid_sdk`'s union carries no unsatisfiable variant, and this pack
/// may not define a Power-local selector type (decision
/// `power_station#the-grid-block-is-the-single-asset-authority`).
AssetSelector parseAssetSelector(Object? raw, String label) {
  if (raw == null) return const AlwaysApplies();
  if (raw is! String || raw.trim().isEmpty) {
    _refuse(label, 'selector', 'must be a string ($kSelectorGrammar)');
  }
  final token = raw.trim();
  final colon = token.indexOf(':');
  final head = colon < 0 ? token : token.substring(0, colon);
  final argument = colon < 0 ? '' : token.substring(colon + 1).trim();
  return switch (head) {
    'unknown' || 'any' => argument.isEmpty
        ? const AlwaysApplies()
        : _refuse(label, 'selector', '"$head" takes no argument'),
    'dart-package' => argument.isEmpty
        ? _refuse(
            label,
            'selector',
            '"dart-package" requires a package name ("dart-package:<name>")',
          )
        : RequiresPackage(argument),
    'decision-register' => argument.isEmpty
        ? const RequiresPath(kDecisionRegisterPath)
        : _refuse(label, 'selector', '"decision-register" takes no argument'),
    'station' => argument.isEmpty
        ? const RequiresPath(kStationStorePath)
        : _refuse(label, 'selector', '"station" takes no argument'),
    'never' => _refuse(
      label,
      'selector',
      '"never" is grammar-valid but cannot be emitted: grid_sdk\'s '
          'AssetSelector union carries no unsatisfiable variant, and this pack '
          'may not define a Power-local selector type',
    ),
    _ => _refuse(
      label,
      'selector',
      'unrecognised selector "$token" (expected $kSelectorGrammar)',
    ),
  };
}

List<AssetArtifact> _artifacts(
  Object? raw,
  String label,
  ArtifactPathProbe pathExists,
) {
  if (raw is! YamlList || raw.isEmpty) {
    _refuse(label, 'artifacts', 'must be a non-empty list');
  }
  final artifacts = <AssetArtifact>[];
  final seenTargets = <AssetDeliveryTarget>{};
  for (var index = 0; index < raw.length; index++) {
    final entry = raw[index];
    if (entry is! YamlMap) {
      _refuse(label, 'artifacts[$index]', 'must be a map');
    }
    final target = _target(entry['target'], label, index);
    if (!seenTargets.add(target)) {
      _refuse(
        label,
        'artifacts[$index].target',
        'duplicate delivery target "${target.name}" — one leg per target',
      );
    }
    final path = _text(entry, 'path', label);
    if (!pathExists(path)) {
      _refuse(label, 'artifacts[$index].path', '"$path" does not exist');
    }
    artifacts.add(
      AssetArtifact(
        target: target,
        path: path,
        arguments: _arguments(entry['args'], label, index),
      ),
    );
  }
  return List<AssetArtifact>.unmodifiable(artifacts);
}

AssetDeliveryTarget _target(Object? raw, String label, int index) {
  for (final target in AssetDeliveryTarget.values) {
    if (target.name == raw) return target;
  }
  _refuse(
    label,
    'artifacts[$index].target',
    'unrecognised target "$raw" (expected one of '
        '${AssetDeliveryTarget.values.map((t) => t.name).join(', ')})',
  );
}

List<AssetArgument> _arguments(Object? raw, String label, int index) {
  if (raw == null) return const <AssetArgument>[];
  if (raw is! YamlList) {
    _refuse(label, 'artifacts[$index].args', 'must be a list');
  }
  return List<AssetArgument>.unmodifiable(<AssetArgument>[
    for (final entry in raw)
      if (entry is! YamlMap)
        _refuse(label, 'artifacts[$index].args', 'every entry is a map')
      else
        AssetArgument(
          name: _text(entry, 'name', label),
          description: _text(entry, 'description', label),
          isRequired: entry['required'] == true,
        ),
  ]);
}

Map<String, String> _mappings(Object? raw, String package) {
  if (raw == null) return const <String, String>{};
  if (raw is! YamlMap) {
    throw GridBlockException(
      'grid: "$package": station_overlay: must be a map',
    );
  }
  final mappings = raw['mappings'];
  if (mappings is! YamlMap) {
    throw GridBlockException(
      'grid: "$package": station_overlay.mappings: must be a map',
    );
  }
  return Map<String, String>.unmodifiable(<String, String>{
    for (final entry in mappings.entries) '${entry.key}': '${entry.value}',
  });
}
