/// The `grid:` block — this package's SINGLE authored asset declaration — and
/// the generator that renders it into the two committed outputs.
///
/// A package participates in the station's compiled asset registry exactly when
/// its pubspec carries a top-level `grid:` block
/// (`the_grid#grid-block-packages-publish-dart-asset-definitions`). This library
/// READS that block and RENDERS `grid_sdk` values; it declares no registry type
/// of its own, and it evaluates no selector — a selector is DECLARED here and
/// resolved above, by a later resolver holding substation facts.
library;

import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:grid_sdk/grid_sdk.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// The marker BOTH generated outputs carry, so a reader tells a generated file
/// from a hand-authored one.
///
/// Deliberately NOT the overlay provenance stamp: that one is the overlay
/// materializer's and embeds the checkout's source ref, which would churn both
/// outputs on every commit and make `--check` fail against an unchanged block.
const String kGridBlockGeneratedMarker =
    'GENERATED by tool/generate_grid_assets.dart';

/// Where the `decision-register` selector points.
const String kDecisionRegisterPath = 'docs/decisions';

/// Where the `station` selector points — the grid's own state store.
const String kStationStorePath = '.grid';

/// The closed selector grammar, rendered for a refusal message.
const String kSelectorGrammar =
    'any, dart-package:<name>, decision-register, station, never, '
    'or omit for unknown';

/// A LOUD refusal from the `grid:` block reader.
///
/// Guards LOUD or GONE (the D-H doctrine, ADR-0008): a malformed block never
/// degrades to a partial pack, and every message names the asset and the field.
final class GridBlockException implements Exception {
  /// Refuses with [message].
  const GridBlockException(this.message);

  /// The refusal, naming the asset and the field.
  final String message;

  @override
  String toString() => message;
}

Never _refuse(String asset, String field, String reason) =>
    throw GridBlockException('grid: asset "$asset": $field: $reason');

/// Answers whether a package-relative artifact path exists.
typedef ArtifactPathProbe = bool Function(String packageRelativePath);

/// One parsed, validated `grid:` block.
final class GridBlock {
  /// Holds the block's [package], its [assets] in declaration order, its
  /// [stationOverlayMappings], and [undeclaredSelectorAssetIds].
  const GridBlock({
    required this.package,
    required this.assets,
    required this.stationOverlayMappings,
    required this.undeclaredSelectorAssetIds,
  });

  /// The vending Dart package.
  final String package;

  /// The declared assets, in declaration order.
  final List<GridAssetDefinition> assets;

  /// The overlay head → target mappings this pack declares.
  final Map<String, String> stationOverlayMappings;

  /// The canonical keys of assets whose block OMITTED `selector`.
  ///
  /// They resolve exactly as `any` does, and stay reportable as UNDECLARED.
  final List<String> undeclaredSelectorAssetIds;
}

/// Parses the `grid:` block out of [pubspecYaml], refusing LOUD on any
/// malformed field, missing artifact path, duplicate [AssetKey], or duplicate
/// [AssetArtifactKey].
///
/// [pathExists] answers whether a package-relative artifact path resolves; it
/// is injected so the block reader stays pure (a Fake in test, `dart:io` in the
/// generator).
GridBlock parseGridBlock({
  required String pubspecYaml,
  required ArtifactPathProbe pathExists,
}) {
  final doc = loadYaml(pubspecYaml);
  if (doc is! YamlMap) {
    throw const GridBlockException('grid: the pubspec is not a YAML map');
  }
  final name = doc['name'];
  if (name is! String || name.trim().isEmpty) {
    throw const GridBlockException(
      'grid: the pubspec declares no package name',
    );
  }
  final block = doc['grid'];
  if (block is! YamlMap) {
    throw GridBlockException(
      'grid: "$name" carries no top-level `grid:` block',
    );
  }
  final rawAssets = block['assets'];
  if (rawAssets is! YamlList) {
    throw GridBlockException('grid: "$name": assets: must be a list');
  }

  final assets = <GridAssetDefinition>[];
  final undeclared = <String>[];
  final seenAssets = <String>{};
  for (final raw in rawAssets) {
    if (raw is! YamlMap) {
      throw GridBlockException('grid: "$name": assets: every entry is a map');
    }
    final id = raw['id'];
    if (id is! String || id.trim().isEmpty) {
      throw GridBlockException(
        'grid: "$name": assets: an entry declares no id',
      );
    }
    final kind = _kind(raw['kind'], id);
    final label = '${kind.name}/$id';
    if (!seenAssets.add(label)) {
      _refuse(label, 'id', 'duplicate logical identity — already declared');
    }
    if (raw['selector'] == null) undeclared.add('$name/$label');
    assets.add(
      GridAssetDefinition(
        assetKey: AssetKey(package: name, kind: kind, id: id),
        description: _text(raw, 'description', label),
        audience: _audience(raw['audience'], label),
        visibility: _visibility(raw['visibility'], label),
        selector: parseAssetSelector(raw['selector'], label),
        teaches: _teaches(raw['teaches'], kind, label),
        artifacts: _artifacts(raw['artifacts'], label, pathExists),
      ),
    );
  }
  return GridBlock(
    package: name,
    assets: List<GridAssetDefinition>.unmodifiable(assets),
    stationOverlayMappings: _mappings(block['station_overlay'], name),
    undeclaredSelectorAssetIds: List<String>.unmodifiable(undeclared),
  );
}

String _text(YamlMap raw, String field, String label) {
  final value = raw[field];
  if (value is! String || value.trim().isEmpty) {
    _refuse(label, field, 'must be a non-empty string');
  }
  return value.trim();
}

AssetKind _kind(Object? raw, String id) {
  for (final kind in AssetKind.values) {
    if (kind.name == raw) return kind;
  }
  _refuse(
    'unknown/$id',
    'kind',
    'unrecognised kind "$raw" (expected one of '
        '${AssetKind.values.map((k) => k.name).join(', ')})',
  );
}

AssetAudience _audience(Object? raw, String label) {
  if (raw == null) return AssetAudience.agent;
  for (final audience in AssetAudience.values) {
    if (audience.name == raw) return audience;
  }
  _refuse(
    label,
    'audience',
    'unrecognised audience "$raw" (expected one of '
        '${AssetAudience.values.map((a) => a.name).join(', ')})',
  );
}

AssetVisibility _visibility(Object? raw, String label) {
  if (raw == null) return AssetVisibility.public;
  for (final visibility in AssetVisibility.values) {
    if (visibility.name == raw) return visibility;
  }
  _refuse(
    label,
    'visibility',
    'unrecognised visibility "$raw" (expected one of '
        '${AssetVisibility.values.map((v) => v.name).join(', ')})',
  );
}

/// One lowercase top-level command name — the shape `grid_sdk`'s pack
/// validation enforces, mirrored here so the YAML boundary refuses FIRST.
final RegExp _taughtCommandPattern = RegExp(r'^[a-z][a-z0-9-]*$');

/// Reads the `teaches:` claim — the top-level commands this asset teaches.
///
/// The COUPLING half of a Packaged AI Asset (`power_station#adr-0001-packaged-
/// ai-asset-skill-command-coupling`): a skill vends prose AND names the
/// deterministic command that prose teaches, so a composing station can fence
/// the pair instead of inferring it. Only a skill teaches; a claim is a list of
/// distinct lowercase command names, in declaration order.
List<String> _teaches(Object? raw, AssetKind kind, String label) {
  if (raw == null) return const <String>[];
  if (raw is! YamlList) _refuse(label, 'teaches', 'must be a list');
  if (raw.isNotEmpty && kind != AssetKind.skill) {
    _refuse(label, 'teaches', 'may be non-empty only for kind "skill"');
  }
  final commands = <String>[];
  final seen = <String>{};
  for (var index = 0; index < raw.length; index++) {
    final entry = raw[index];
    if (entry is! String || !_taughtCommandPattern.hasMatch(entry)) {
      _refuse(
        label,
        'teaches[$index]',
        'must be one lowercase top-level command name matching '
            '${_taughtCommandPattern.pattern}',
      );
    }
    if (!seen.add(entry)) {
      _refuse(label, 'teaches[$index]', 'duplicate command "$entry"');
    }
    commands.add(entry);
  }
  return List<String>.unmodifiable(commands);
}

/// Maps one CLOSED selector token onto the `grid_sdk` [AssetSelector] union.
///
/// `null` (omitted), `unknown`, and `any` all yield [AlwaysApplies]; the
/// omission is separately reported through
/// [GridBlock.undeclaredSelectorAssetIds]. `never` is grammar-valid and
/// REFUSED: `grid_sdk`'s union carries no unsatisfiable variant, and this pack
/// may not define a Power-local selector type (decision
/// `power_station#the-grid-block-is-the-single-asset-authority`).
AssetSelector parseAssetSelector(Object? raw, String label) {
  if (raw == null) return const AlwaysApplies();
  if (raw is! String || raw.trim().isEmpty) {
    _refuse(label, 'selector', 'must be a string ($kSelectorGrammar)');
  }
  final token = raw.trim();
  final colon = token.indexOf(':');
  final head = colon < 0 ? token : token.substring(0, colon);
  final argument = colon < 0 ? '' : token.substring(colon + 1).trim();
  return switch (head) {
    'unknown' || 'any' =>
      argument.isEmpty
          ? const AlwaysApplies()
          : _refuse(label, 'selector', '"$head" takes no argument'),
    'dart-package' =>
      argument.isEmpty
          ? _refuse(
              label,
              'selector',
              '"dart-package" requires a package name ("dart-package:<name>")',
            )
          : RequiresPackage(argument),
    'decision-register' =>
      argument.isEmpty
          ? const RequiresPath(kDecisionRegisterPath)
          : _refuse(label, 'selector', '"decision-register" takes no argument'),
    'station' =>
      argument.isEmpty
          ? const RequiresPath(kStationStorePath)
          : _refuse(label, 'selector', '"station" takes no argument'),
    'never' => _refuse(
      label,
      'selector',
      '"never" is grammar-valid but cannot be emitted: grid_sdk\'s '
          'AssetSelector union carries no unsatisfiable variant, and this pack '
          'may not define a Power-local selector type',
    ),
    _ => _refuse(
      label,
      'selector',
      'unrecognised selector "$token" (expected $kSelectorGrammar)',
    ),
  };
}

List<AssetArtifact> _artifacts(
  Object? raw,
  String label,
  ArtifactPathProbe pathExists,
) {
  if (raw is! YamlList || raw.isEmpty) {
    _refuse(label, 'artifacts', 'must be a non-empty list');
  }
  final artifacts = <AssetArtifact>[];
  final seenTargets = <AssetDeliveryTarget>{};
  for (var index = 0; index < raw.length; index++) {
    final entry = raw[index];
    if (entry is! YamlMap) {
      _refuse(label, 'artifacts[$index]', 'must be a map');
    }
    final target = _target(entry['target'], label, index);
    if (!seenTargets.add(target)) {
      _refuse(
        label,
        'artifacts[$index].target',
        'duplicate delivery target "${target.name}" — one leg per target',
      );
    }
    final path = _text(entry, 'path', label);
    if (!pathExists(path)) {
      _refuse(label, 'artifacts[$index].path', '"$path" does not exist');
    }
    artifacts.add(
      AssetArtifact(
        target: target,
        path: path,
        arguments: _arguments(entry['args'], label, index),
      ),
    );
  }
  return List<AssetArtifact>.unmodifiable(artifacts);
}

AssetDeliveryTarget _target(Object? raw, String label, int index) {
  for (final target in AssetDeliveryTarget.values) {
    if (target.name == raw) return target;
  }
  _refuse(
    label,
    'artifacts[$index].target',
    'unrecognised target "$raw" (expected one of '
        '${AssetDeliveryTarget.values.map((t) => t.name).join(', ')})',
  );
}

List<AssetArgument> _arguments(Object? raw, String label, int index) {
  if (raw == null) return const <AssetArgument>[];
  if (raw is! YamlList) {
    _refuse(label, 'artifacts[$index].args', 'must be a list');
  }
  return List<AssetArgument>.unmodifiable(<AssetArgument>[
    for (final entry in raw)
      if (entry is! YamlMap)
        _refuse(label, 'artifacts[$index].args', 'every entry is a map')
      else
        AssetArgument(
          name: _text(entry, 'name', label),
          description: _text(entry, 'description', label),
          isRequired: entry['required'] == true,
        ),
  ]);
}

Map<String, String> _mappings(Object? raw, String package) {
  if (raw == null) return const <String, String>{};
  if (raw is! YamlMap) {
    throw GridBlockException(
      'grid: "$package": station_overlay: must be a map',
    );
  }
  final mappings = raw['mappings'];
  if (mappings is! YamlMap) {
    throw GridBlockException(
      'grid: "$package": station_overlay.mappings: must be a map',
    );
  }
  return Map<String, String>.unmodifiable(<String, String>{
    for (final entry in mappings.entries) '${entry.key}': '${entry.value}',
  });
}

/// Renders [block] as the public Dart library a station composes.
///
/// Emits VALUES, never subclasses: one `static const GridAssetDefinition` per
/// logical asset (`the_grid#asset-definitions-are-const-collections-are-validated`
/// keeps the definition `const`), and ONE `static final
/// GridAssetPackDefinition` — the collections validate at construction, so they
/// are deeply immutable rather than `const`.
String renderGridAssetPackLibrary(GridBlock block) {
  final buffer = StringBuffer()
    ..writeln('// $kGridBlockGeneratedMarker — do not edit.')
    ..writeln(
      '// Source of truth: the `grid:` block in '
      'packages/${block.package}/pubspec.yaml.',
    )
    ..writeln('// Regenerate: dart run tool/generate_grid_assets.dart')
    ..writeln()
    ..writeln('/// The asset surface `${block.package}` vends, as the neutral')
    ..writeln('/// `grid_sdk` declaration contract.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:grid_sdk/grid_sdk.dart';")
    ..writeln()
    ..writeln('/// The `${block.package}` asset pack.')
    ..writeln('abstract final class GridAssetsPack {')
    ..writeln('  /// The vending Dart package.')
    ..writeln("  static const String package = '${block.package}';")
    ..writeln();
  for (final asset in block.assets) {
    buffer
      ..writeln('  /// `${asset.assetKey.canonical}`.')
      ..writeln(
        '  static const GridAssetDefinition '
        '${assetFieldName(asset.assetKey)} = GridAssetDefinition(',
      )
      ..writeln('    assetKey: AssetKey(')
      ..writeln('      package: package,')
      ..writeln('      kind: AssetKind.${asset.assetKey.kind.name},')
      ..writeln("      id: '${asset.assetKey.id}',")
      ..writeln('    ),')
      ..writeln('    description: ${_dartString(asset.description)},')
      ..writeln('    audience: AssetAudience.${asset.audience.name},')
      ..writeln('    visibility: AssetVisibility.${asset.visibility.name},')
      ..writeln('    selector: ${selectorExpression(asset.selector)},');
    if (asset.teaches.isNotEmpty) {
      buffer.writeln(
        '    teaches: <String>['
        '${asset.teaches.map(_dartString).join(', ')}],',
      );
    }
    buffer.writeln('    artifacts: <AssetArtifact>[');
    for (final artifact in asset.artifacts) {
      buffer
        ..writeln('      AssetArtifact(')
        ..writeln(
          '        target: AssetDeliveryTarget.${artifact.target.name},',
        )
        ..writeln("        path: '${artifact.path}',");
      if (artifact.arguments.isNotEmpty) {
        buffer.writeln('        arguments: <AssetArgument>[');
        for (final argument in artifact.arguments) {
          buffer
            ..writeln('          AssetArgument(')
            ..writeln("            name: '${argument.name}',")
            ..writeln(
              '            description: ${_dartString(argument.description)},',
            )
            ..writeln('            isRequired: ${argument.isRequired},')
            ..writeln('          ),');
        }
        buffer.writeln('        ],');
      }
      buffer.writeln('      ),');
    }
    buffer
      ..writeln('    ],')
      ..writeln('  );')
      ..writeln();
  }
  buffer
    ..writeln('  /// Every declared asset, in declaration order.')
    ..writeln(
      '  static const List<GridAssetDefinition> assets = '
      '<GridAssetDefinition>[',
    );
  for (final asset in block.assets) {
    buffer.writeln('    ${assetFieldName(asset.assetKey)},');
  }
  buffer
    ..writeln('  ];')
    ..writeln()
    ..writeln('  /// The validated pack. Built, not `const`: the collections')
    ..writeln('  /// validate duplicates at construction')
    ..writeln(
      '  /// (`the_grid#asset-definitions-are-const-collections-are-'
      'validated`).',
    )
    ..writeln('  static final GridAssetPackDefinition definition =')
    ..writeln(
      '      GridAssetPackDefinition(package: package, assets: assets);',
    )
    ..writeln()
    ..writeln("  /// This pack's overlay head → target mappings.")
    ..writeln('  static const Map<String, String> stationOverlayMappings =')
    ..writeln('      <String, String>{');
  for (final entry in block.stationOverlayMappings.entries) {
    buffer.writeln("        '${entry.key}': '${entry.value}',");
  }
  buffer
    ..writeln('      };')
    ..writeln('}');
  return buffer.toString();
}

/// The generated field name for [key] — `<kind><PascalCaseId>`.
String assetFieldName(AssetKey key) {
  final words = key.id
      .split(RegExp('[^A-Za-z0-9]+'))
      .where((word) => word.isNotEmpty);
  return key.kind.name +
      words.map((word) => word[0].toUpperCase() + word.substring(1)).join();
}

/// The Dart source expression for [selector] — an exhaustive `switch` over the
/// sealed `grid_sdk` union, so a new variant breaks this renderer loudly.
String selectorExpression(AssetSelector selector) => switch (selector) {
  AlwaysApplies() => 'AlwaysApplies()',
  RequiresPackage(:final packageName) => "RequiresPackage('$packageName')",
  RequiresPath(:final relativePath) => "RequiresPath('$relativePath')",
  RequiresAll(:final selectors) =>
    'RequiresAll(<AssetSelector>['
        '${selectors.map(selectorExpression).join(', ')}])',
};

String _dartString(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll(r'$', r'\$')
      .replaceAll("'", r"\'");
  return "'$escaped'";
}

String _yamlString(String value) {
  final escaped = value.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
  return '"$escaped"';
}

/// Renders [block] as the MCP-shaped compatibility mirror
/// (`extension/mcp/config.yaml`, the `package:extension_discovery` shape).
///
/// Carries ONLY MCP concepts. The grid-only `kind`, `selector`, `teaches`, and
/// the non-MCP delivery legs stay in the block and in the generated Dart. This
/// mirror is compatibility output, never a second claim authority. `agent`,
/// `hook`, and `settings` assets are not mirrored — MCP has no section for
/// them.
String renderMcpConfig(GridBlock block) {
  final resources = <GridAssetDefinition>[];
  final prompts = <GridAssetDefinition>[];
  final skills = <GridAssetDefinition>[];
  for (final asset in block.assets) {
    switch (asset.assetKey.kind) {
      case AssetKind.resource:
      case AssetKind.rubric:
        resources.add(asset);
      case AssetKind.prompt:
        prompts.add(asset);
      case AssetKind.skill:
        skills.add(asset);
      case AssetKind.agent:
      case AssetKind.hook:
      case AssetKind.settings:
        break;
    }
  }
  final buffer = StringBuffer()
    ..writeln('# $kGridBlockGeneratedMarker — do not edit.')
    ..writeln(
      '# Source of truth: the `grid:` block in '
      'packages/${block.package}/pubspec.yaml.',
    )
    ..writeln('#')
    ..writeln(
      '# The MCP-shaped compatibility mirror of that block, authored in',
    )
    ..writeln('# the Dart/Flutter "Packaged AI Assets" format (per')
    ..writeln('# flutter.dev/go/packaged-ai-assets — the')
    ..writeln('# package:extension_discovery `extension/mcp/config.yaml`')
    ..writeln('# shape). It carries only MCP concepts; grid-only kind,')
    ..writeln('# selector, and non-MCP delivery legs stay in the block and in')
    ..writeln('# lib/src/assets/grid_asset_pack.dart.')
    ..writeln('name: ${block.package}')
    ..writeln('version: 1');
  _writeMcpSection(
    buffer,
    heading: 'resources',
    preamble: '# Rubric prose — one resource per committee lane.',
    assets: resources,
    leg: AssetDeliveryTarget.mcp,
    withAudience: false,
  );
  _writeMcpSection(
    buffer,
    heading: 'prompts',
    preamble: '# Prompts — mustache-templated instruction bodies.',
    assets: prompts,
    leg: AssetDeliveryTarget.mcp,
    withAudience: false,
  );
  _writeMcpSection(
    buffer,
    heading: 'skills',
    preamble:
        '# Skills — the agentskills SKILL.md assets the station_overlay\n'
        '# vends. `audience: operator` is the DENY-list a build agent brief\n'
        '# reads through `operatorSkillIds`; the claude leg is mirrored here,\n'
        '# and every other leg lives in the block.',
    assets: skills,
    leg: AssetDeliveryTarget.claude,
    withAudience: true,
  );
  buffer
    ..writeln('station_overlay:')
    ..writeln('  mappings:');
  for (final entry in block.stationOverlayMappings.entries) {
    buffer.writeln('    ${entry.key}: ${entry.value}');
  }
  return buffer.toString();
}

void _writeMcpSection(
  StringBuffer buffer, {
  required String heading,
  required String preamble,
  required List<GridAssetDefinition> assets,
  required AssetDeliveryTarget leg,
  required bool withAudience,
}) {
  if (assets.isEmpty) return;
  buffer
    ..writeln()
    ..writeln(preamble)
    ..writeln('$heading:');
  for (final asset in assets) {
    final artifact = _legOf(asset, leg);
    buffer
      ..writeln('  - id: ${asset.assetKey.id}')
      ..writeln('    description: ${_yamlString(asset.description)}')
      ..writeln('    path: ${_mcpPath(artifact.path)}')
      ..writeln('    visibility: ${asset.visibility.name}');
    if (withAudience) {
      buffer.writeln('    audience: ${_mcpAudience(asset.audience)}');
    }
    if (artifact.arguments.isEmpty) continue;
    buffer.writeln('    args:');
    for (final argument in artifact.arguments) {
      buffer
        ..writeln('      - name: ${argument.name}')
        ..writeln('        description: ${_yamlString(argument.description)}')
        ..writeln('        required: ${argument.isRequired}');
    }
  }
}

AssetArtifact _legOf(GridAssetDefinition asset, AssetDeliveryTarget target) {
  for (final artifact in asset.artifacts) {
    if (artifact.target == target) return artifact;
  }
  _refuse(
    '${asset.assetKey.kind.name}/${asset.assetKey.id}',
    'artifacts',
    'the MCP mirror needs a ${target.name} leg and none is declared',
  );
}

/// MCP paths are relative to `extension/`; the block's are package-relative.
String _mcpPath(String packageRelative) =>
    packageRelative.startsWith('extension/')
    ? packageRelative.substring('extension/'.length)
    : packageRelative;

/// The MCP spelling of an audience — exhaustive over the `grid_sdk` enum. The
/// manifest's long-standing word for `human` is `operator`; `both` is
/// agent-invocable, so it mirrors as `agent`.
String _mcpAudience(AssetAudience audience) => switch (audience) {
  AssetAudience.human => 'operator',
  AssetAudience.agent => 'agent',
  AssetAudience.both => 'agent',
};

/// The generated Dart declaration, relative to the package root.
const String kGeneratedPackPath = 'lib/src/assets/grid_asset_pack.dart';

/// The generated MCP mirror, relative to the package root.
const String kGeneratedMcpPath = 'extension/mcp/config.yaml';

/// Normalizes a rendered output so a fresh render is byte-equal to what the
/// repository formatter would leave on disk.
///
/// Dart outputs go through the same [DartFormatter] `dart format` runs; every
/// other output — the YAML mirror included — passes through untouched.
String _formatGeneratedOutput(String relativePath, String source) {
  if (p.extension(relativePath) != '.dart') return source;
  return DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format(source, uri: relativePath);
}

/// Regenerates — or, with [check], VERIFIES — both generated outputs from the
/// `grid:` block at `<packageRoot>/pubspec.yaml`.
///
/// ATOMIC: both outputs are rendered from ONE parse before either is written,
/// so a malformed block ([GridBlockException]) leaves both files untouched.
/// Generated Dart is formatter-normalized before BOTH the [check] comparison
/// and the write, so a fresh render survives `dart format --set-exit-if-changed`.
/// Returns a process exit code — `0` current, `1` stale under [check].
/// [out] defaults to `stdout`.
int runGridAssetsGenerator({
  required String packageRoot,
  bool check = false,
  StringSink? out,
}) {
  final sink = out ?? stdout;
  final block = parseGridBlock(
    pubspecYaml: File(p.join(packageRoot, 'pubspec.yaml')).readAsStringSync(),
    pathExists: (relative) =>
        File(p.join(packageRoot, relative)).existsSync() ||
        Directory(p.join(packageRoot, relative)).existsSync(),
  );
  final rendered = <String, String>{
    kGeneratedPackPath: renderGridAssetPackLibrary(block),
    kGeneratedMcpPath: renderMcpConfig(block),
  };
  final outputs = <String, String>{
    for (final entry in rendered.entries)
      entry.key: _formatGeneratedOutput(entry.key, entry.value),
  };
  final report =
      '${block.assets.length} assets, '
      '${block.undeclaredSelectorAssetIds.length} with an UNDECLARED selector';
  if (check) {
    final stale = <String>[
      for (final entry in outputs.entries)
        if (_currentText(packageRoot, entry.key) != entry.value) entry.key,
    ];
    for (final path in stale) {
      sink.writeln(
        'STALE $path — run `dart run tool/generate_grid_assets.dart`',
      );
    }
    sink.writeln('grid: $report');
    return stale.isEmpty ? 0 : 1;
  }
  for (final entry in outputs.entries) {
    File(p.join(packageRoot, entry.key)).writeAsStringSync(entry.value);
  }
  sink.writeln('grid: wrote ${outputs.length} outputs — $report');
  return 0;
}

String? _currentText(String packageRoot, String relative) {
  final file = File(p.join(packageRoot, relative));
  return file.existsSync() ? file.readAsStringSync() : null;
}
