// GENERATED by tool/generate_grid_assets.dart — do not edit.
// Source of truth: the `grid:` block in packages/grid_assets/pubspec.yaml.
// Regenerate: dart run tool/generate_grid_assets.dart

/// The asset surface `grid_assets` vends, as the neutral
/// `grid_sdk` declaration contract.
library;

import 'package:grid_sdk/grid_sdk.dart';

/// The `grid_assets` asset pack.
abstract final class GridAssetsPack {
  /// The vending Dart package.
  static const String package = 'grid_assets';

  /// `grid_assets/rubric/code-validation`.
  static const GridAssetDefinition rubricCodeValidation = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'code-validation',
    ),
    description: 'The GATING lane — runs the bead\'s own Validation Plan; F on any non-zero command.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/code-validation.md',
      ),
    ],
  );

  /// `grid_assets/rubric/spec-adherence`.
  static const GridAssetDefinition rubricSpecAdherence = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'spec-adherence',
    ),
    description: 'Does the diff implement the bead\'s Implementation Plan + acceptance criteria?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/spec-adherence.md',
      ),
    ],
  );

  /// `grid_assets/rubric/regression-risk`.
  static const GridAssetDefinition rubricRegressionRisk = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'regression-risk',
    ),
    description: 'The blast radius — how likely is the change to break existing behavior?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/regression-risk.md',
      ),
    ],
  );

  /// `grid_assets/rubric/test-coverage`.
  static const GridAssetDefinition rubricTestCoverage = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'test-coverage',
    ),
    description: 'Are the changes covered by MEANINGFUL (non-vacuous) tests?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/test-coverage.md',
      ),
    ],
  );

  /// `grid_assets/rubric/spec-validation`.
  static const GridAssetDefinition rubricSpecValidation = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'spec-validation',
    ),
    description: 'The GATING spec lane — a deterministic structural check over the bead\'s spec; F on any missing section or placeholder.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/spec-validation.md',
      ),
    ],
  );

  /// `grid_assets/rubric/coherence`.
  static const GridAssetDefinition rubricCoherence = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'coherence',
    ),
    description: 'Does the spec carve scope cleanly from sibling beads AND extend existing code rather than duplicate it?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/coherence.md',
      ),
    ],
  );

  /// `grid_assets/rubric/adr-alignment`.
  static const GridAssetDefinition rubricAdrAlignment = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'adr-alignment',
    ),
    description: 'Does the spec cite and align with the substation\'s docs/adr register (ADR-0000 amendments included)?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/adr-alignment.md',
      ),
    ],
  );

  /// `grid_assets/rubric/decision-alignment`.
  static const GridAssetDefinition rubricDecisionAlignment = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'decision-alignment',
    ),
    description: 'Does the spec cite and align with every recorded decision the station\'s ROSTER union governs its touched surfaces with?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: RequiresPath('docs/decisions'),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/decision-alignment.md',
      ),
    ],
  );

  /// `grid_assets/rubric/acceptance-testability`.
  static const GridAssetDefinition rubricAcceptanceTestability = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'acceptance-testability',
    ),
    description: 'Are the acceptance criteria testable by exact commands, with a 1:1 validation-plan mapping?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/acceptance-testability.md',
      ),
    ],
  );

  /// `grid_assets/rubric/plan-completeness`.
  static const GridAssetDefinition rubricPlanCompleteness = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'plan-completeness',
    ),
    description: 'Is the implementation plan literal and decision-free — exact Dart code, file paths, test commands, commits?',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/plan-completeness.md',
      ),
    ],
  );

  /// `grid_assets/rubric/bead-readiness`.
  static const GridAssetDefinition rubricBeadReadiness = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'bead-readiness',
    ),
    description: 'The INTAKE lens — is the BEAD ready to specify (scope, acceptance shape, cited constraints, a decided approach)? D or worse HOLDS it for refinement.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/bead-readiness.md',
      ),
    ],
  );

  /// `grid_assets/rubric/citation-paths-resolve`.
  static const GridAssetDefinition rubricCitationPathsResolve = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'citation-paths-resolve',
    ),
    description: 'The DOCS gating lane — every file path a changed doc cites must resolve in the tree.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/citation-paths-resolve.md',
      ),
    ],
  );

  /// `grid_assets/rubric/terminology-ban`.
  static const GridAssetDefinition rubricTerminologyBan = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'terminology-ban',
    ),
    description: 'The DOCS gating lane — the org seam word is `extension`; the banned word is reserved for third-party proper nouns.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/terminology-ban.md',
      ),
    ],
  );

  /// `grid_assets/rubric/section-structure`.
  static const GridAssetDefinition rubricSectionStructure = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.rubric,
      id: 'section-structure',
    ),
    description: 'The DOCS gating lane — the sections a bead names (metadata.docs_sections) must be present in every changed doc.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/rubrics/section-structure.md',
      ),
    ],
  );

  /// `grid_assets/prompt/critic`.
  static const GridAssetDefinition promptCritic = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.prompt,
      id: 'critic',
    ),
    description: 'One adversarial critic, grading the work against a single rubric in isolation.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/prompts/critic.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'rubric',
            description: 'The rubric id this critic grades against (the lane).',
            isRequired: true,
          ),
          AssetArgument(
            name: 'rubricText',
            description: 'The rubric\'s prose bands, loaded from resources/<rubric>.',
            isRequired: true,
          ),
          AssetArgument(
            name: 'bead',
            description: 'The full work bead under review (title/task/design/acceptance/notes).',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/prompt/spec-critic`.
  static const GridAssetDefinition promptSpecCritic = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.prompt,
      id: 'spec-critic',
    ),
    description: 'One adversarial spec-readiness critic, grading the bead\'s SPEC (not a diff) against a single rubric in isolation.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/prompts/spec-critic.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'rubric',
            description: 'The rubric id this critic grades against (the lane).',
            isRequired: true,
          ),
          AssetArgument(
            name: 'rubricText',
            description: 'The rubric\'s prose bands, loaded from resources/<rubric>.',
            isRequired: true,
          ),
          AssetArgument(
            name: 'bead',
            description: 'The full work bead whose acceptance + design fields are the spec under review.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/prompt/readiness`.
  static const GridAssetDefinition promptReadiness = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.prompt,
      id: 'readiness',
    ),
    description: 'The cheap pre-specify intake lens, grading the work BEAD itself (no spec and no diff exists yet).',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/prompts/readiness.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'rubric',
            description: 'The rubric id this lens grades against.',
            isRequired: true,
          ),
          AssetArgument(
            name: 'rubricText',
            description: 'The rubric\'s prose bands, loaded from resources/<rubric>.',
            isRequired: true,
          ),
          AssetArgument(
            name: 'bead',
            description: 'The full work bead under intake (title/task/design/acceptance/notes).',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/prompt/discovery`.
  static const GridAssetDefinition promptDiscovery = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.prompt,
      id: 'discovery',
    ),
    description: 'One read-only explorer in the discovery circuit — gathers context and CITES any offence; it grades nothing.',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.mcp,
        path: 'extension/prompts/discovery.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'lens',
            description: 'The lens this explorer runs (explore-code | explore-decision | explore-prior-art).',
            isRequired: true,
          ),
          AssetArgument(
            name: 'lensBrief',
            description: 'The lens\'s angle — what this explorer looks for.',
            isRequired: true,
          ),
          AssetArgument(
            name: 'bead',
            description: 'The full work bead being explored (title/task/design/acceptance/notes).',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/skill/asset-author`.
  static const GridAssetDefinition skillAssetAuthor = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'asset-author',
    ),
    description: 'Author and install grid assets through B-style in-tree providers: watched nullable dependencies, diagnostic unavailability, explicit create/value ownership, scoped overrides, and assembly-only boot.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: RequiresPackage('grid_sdk'),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/asset-author/SKILL.md',
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/asset-author/SKILL.md',
      ),
    ],
  );

  /// `grid_assets/skill/discover`.
  static const GridAssetDefinition skillDiscover = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'discover',
    ),
    description: 'The grid home\'s HITL front door — dispatches on arg shape (topic research / bead advisory / bead directed), researches via the vended `search` Command, and on the human\'s yes files an ephemeral staged bead and starts the design conversation (hand-off: specify).',
    audience: AssetAudience.agent,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/discover/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name (e.g. `space`) — the verb the skill\'s search calls ride.',
            isRequired: true,
          ),
        ],
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/discover/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name (e.g. `space`) — the verb the skill\'s search calls ride.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/skill/gate-medicine`.
  static const GridAssetDefinition skillGateMedicine = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'gate-medicine',
    ),
    description: 'Diagnose and clear gated sessions — read the worktree critique artifacts, separate systemic failures from genuinely bad work, and re-arm with a rework round.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/gate-medicine/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb its rework calls ride.',
            isRequired: true,
          ),
        ],
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/gate-medicine/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb its rework calls ride.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/skill/handoff`.
  static const GridAssetDefinition skillHandoff = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'handoff',
    ),
    description: 'Write the seat\'s own handoff onto its Agent Disc, bank the durable learnings as separate disc notes, index it, and end the turn with the one line that tells the OUTER harness to compact, clear, or relaunch. Also the successor\'s read: consume the newest handoff and delete it.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/handoff/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb the skill\'s `status` read rides.',
            isRequired: true,
          ),
        ],
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/handoff/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb the skill\'s `status` read rides.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/skill/harvest-review`.
  static const GridAssetDefinition skillHarvestReview = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'harvest-review',
    ),
    description: 'Review and land what a station built — verify each terminal session\'s branch delta, committee grades, and validation plan in the real worktree, then push and open a PR with receipts.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/harvest-review/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb its rework calls ride.',
            isRequired: true,
          ),
        ],
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/harvest-review/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb its rework calls ride.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/skill/intake-refinement`.
  static const GridAssetDefinition skillIntakeRefinement = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'intake-refinement',
    ),
    description: 'Shape work beads so a resident station can drive them — the required validation_plan metadata, driveable issue types, dependency wiring, and stamped grid.approved approval via the approve verb.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/intake-refinement/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name (e.g. `space`) — the verb its boot/status/down calls ride.',
            isRequired: true,
          ),
        ],
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/intake-refinement/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name (e.g. `space`) — the verb its boot/status/down calls ride.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/skill/release`.
  static const GridAssetDefinition skillRelease = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'release',
    ),
    description: 'Cut a disciplined pub.dev release — the consolidated genesis+lenny publishing playbook. Owns the judgement (when to publish, patch vs. breaking, breaking-CHANGELOG framing, tag-drift reconciliation) and CALLS the vended `dart release` Command for the deterministic work (version math, scrub gate, dry-run, pub.dev poll, dependency order).',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/release/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb the skill\'s `dart release` calls ride.',
            isRequired: true,
          ),
        ],
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/release/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name — the verb the skill\'s `dart release` calls ride.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/skill/station-operations`.
  static const GridAssetDefinition skillStationOperations = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.skill,
      id: 'station-operations',
    ),
    description: 'Operate the resident station — boot, bounce, tear down, read status, seed a grid home\'s state store, and diagnose a station that is up but driving nothing.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/skills/station-operations/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name (e.g. `space`) — the verb its boot/status/down calls ride.',
            isRequired: true,
          ),
        ],
      ),
      AssetArtifact(
        target: AssetDeliveryTarget.agents,
        path: 'extension/station_overlay/agents/skills/station-operations/SKILL.md',
        arguments: <AssetArgument>[
          AssetArgument(
            name: 'runner',
            description: 'The composing station\'s executable name (e.g. `space`) — the verb its boot/status/down calls ride.',
            isRequired: true,
          ),
        ],
      ),
    ],
  );

  /// `grid_assets/agent/governor`.
  static const GridAssetDefinition agentGovernor = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.agent,
      id: 'governor',
    ),
    description: 'The governor seat\'s persona, tool surface, and cost posture.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/agents/governor.md',
      ),
    ],
  );

  /// `grid_assets/settings/harness`.
  static const GridAssetDefinition settingsHarness = GridAssetDefinition(
    assetKey: AssetKey(
      package: package,
      kind: AssetKind.settings,
      id: 'harness',
    ),
    description: 'The harness settings this pack contributes to an operator seat.',
    audience: AssetAudience.human,
    visibility: AssetVisibility.public,
    selector: AlwaysApplies(),
    artifacts: <AssetArtifact>[
      AssetArtifact(
        target: AssetDeliveryTarget.claude,
        path: 'extension/station_overlay/claude/settings.json',
      ),
    ],
  );

  /// Every declared asset, in declaration order.
  static const List<GridAssetDefinition> assets = <GridAssetDefinition>[
    rubricCodeValidation,
    rubricSpecAdherence,
    rubricRegressionRisk,
    rubricTestCoverage,
    rubricSpecValidation,
    rubricCoherence,
    rubricAdrAlignment,
    rubricDecisionAlignment,
    rubricAcceptanceTestability,
    rubricPlanCompleteness,
    rubricBeadReadiness,
    rubricCitationPathsResolve,
    rubricTerminologyBan,
    rubricSectionStructure,
    promptCritic,
    promptSpecCritic,
    promptReadiness,
    promptDiscovery,
    skillAssetAuthor,
    skillDiscover,
    skillGateMedicine,
    skillHandoff,
    skillHarvestReview,
    skillIntakeRefinement,
    skillRelease,
    skillStationOperations,
    agentGovernor,
    settingsHarness,
  ];

  /// The validated pack. Built, not `const`: the collections
  /// validate duplicates at construction
  /// (`the_grid#asset-definitions-are-const-collections-are-validated`).
  static final GridAssetPackDefinition definition =
      GridAssetPackDefinition(package: package, assets: assets);

  /// This pack's overlay head → target mappings.
  static const Map<String, String> stationOverlayMappings =
      <String, String>{
        'claude': '.claude',
      };
}
