/// Generation-time discovery and rendering for a station asset registrant.
///
/// Package discovery reads the station's explicit package config. Runtime
/// consumers import only the generated registrant and its static pack
/// references.
library;

import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:grid_sdk/grid_sdk.dart';
import 'package:package_config/package_config.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

import 'grid_block.dart';

/// The provenance marker carried by every generated station registrant.
const String kStationAssetRegistryGeneratedMarker =
    'GENERATED by tool/generate_station_asset_registry.dart';

/// The default station-relative generated registrant path.
const String kGeneratedStationAssetRegistryPath =
    'lib/station_asset_registry.dart';

/// A malformed station graph or participating package.
final class StationAssetRegistryException implements Exception {
  /// Refuses generation with [message].
  const StationAssetRegistryException(this.message);

  /// The complete refusal.
  final String message;

  @override
  String toString() => message;
}

/// A lockfile whose packages are not all present in package config.
final class StalePackageGraphException implements Exception {
  /// Records every missing package in deterministic order.
  StalePackageGraphException(Iterable<String> packageNames)
    : packageNames = List<String>.unmodifiable(
        <String>[...packageNames]..sort(),
      );

  /// Lockfile packages absent from package config.
  final List<String> packageNames;

  /// The operator-facing refusal.
  String get message =>
      'stale Dart package graph: pubspec.lock packages missing from '
      '.dart_tool/package_config.json: ${packageNames.join(', ')}; '
      'run `dart pub get` in the station root';

  @override
  String toString() => message;
}

/// One participating package resolved from the station package config.
final class ResolvedGridAssetPack {
  /// Describes the package and its validated generated-pack contribution.
  const ResolvedGridAssetPack({
    required this.name,
    required this.version,
    required this.root,
    required this.publicLibraryUri,
    required this.definition,
  });

  /// Package identity from package config and pubspec.
  final String name;

  /// Authored pubspec version.
  final String version;

  /// Absolute resolved package root.
  final String root;

  /// Public package library exporting `GridAssetsPack`.
  final Uri publicLibraryUri;

  /// The validated definition used to preflight generation.
  final GridAssetPackDefinition definition;

  /// Declared assets, in their package declaration order.
  List<GridAssetDefinition> get assets => definition.assets;
}

/// Resolves all packages participating in [stationRoot]'s asset registry.
///
/// The package config is the enumeration authority. The lockfile is only a
/// staleness oracle: extra package-config entries, including workspace
/// members, remain eligible.
List<ResolvedGridAssetPack> resolveStationGridAssetPacks({
  required String stationRoot,
}) {
  final configFile = File(
    p.join(stationRoot, '.dart_tool', 'package_config.json'),
  );
  final lockFile = File(p.join(stationRoot, 'pubspec.lock'));
  if (!configFile.existsSync()) {
    throw StationAssetRegistryException(
      'no package config at ${configFile.path}; run `dart pub get` in the '
      'station root',
    );
  }
  if (!lockFile.existsSync()) {
    throw StationAssetRegistryException(
      'no lockfile at ${lockFile.path}; the station registry requires its '
      'pubspec.lock staleness oracle',
    );
  }

  final packageConfig = _parsePackageConfig(configFile);
  final packagesByName = <String, Package>{
    for (final package in packageConfig.packages) package.name: package,
  };
  final lock = _yamlMap(lockFile, 'pubspec.lock');
  final locked = lock['packages'];
  if (locked is! YamlMap) {
    throw StationAssetRegistryException(
      '${lockFile.path}: packages must be a YAML map',
    );
  }
  final missing = <String>[
    for (final name in locked.keys.map((key) => '$key'))
      if (!packagesByName.containsKey(name)) name,
  ];
  if (missing.isNotEmpty) throw StalePackageGraphException(missing);

  final packages = <Package>[...packageConfig.packages]
    ..sort((a, b) => a.name.compareTo(b.name));
  final resolved = <ResolvedGridAssetPack>[];
  for (final package in packages) {
    if (package.root.scheme != 'file') {
      throw StationAssetRegistryException(
        'package "${package.name}" has non-file root ${package.root}',
      );
    }
    final root = p.normalize(Directory.fromUri(package.root).absolute.path);
    final pubspecFile = File(p.join(root, 'pubspec.yaml'));
    if (!pubspecFile.existsSync()) {
      throw StationAssetRegistryException(
        'package "${package.name}" has no pubspec at ${pubspecFile.path}',
      );
    }
    final source = pubspecFile.readAsStringSync();
    final pubspec = _parseYamlMap(source, pubspecFile.path, 'package pubspec');
    if (!pubspec.containsKey('grid')) continue;

    final declaredName = pubspec['name'];
    if (declaredName != package.name) {
      throw StationAssetRegistryException(
        'package config names "${package.name}" but ${pubspecFile.path} '
        'declares "$declaredName"',
      );
    }
    final version = pubspec['version'];
    if (version is! String || version.trim().isEmpty) {
      throw StationAssetRegistryException(
        'participating package "${package.name}" declares no version',
      );
    }
    final publicLibraryUri = Uri.parse(
      'package:${package.name}/${package.name}.dart',
    );
    final publicLibrary = File.fromUri(
      package.packageUriRoot.resolve('${package.name}.dart'),
    );
    if (!publicLibrary.existsSync()) {
      throw StationAssetRegistryException(
        'participating package "${package.name}" does not expose '
        '$publicLibraryUri at ${publicLibrary.path}',
      );
    }

    final block = parseGridBlock(
      pubspecYaml: source,
      pathExists: (relativePath) =>
          File(p.join(root, relativePath)).existsSync() ||
          Directory(p.join(root, relativePath)).existsSync(),
    );
    resolved.add(
      ResolvedGridAssetPack(
        name: package.name,
        version: version,
        root: root,
        publicLibraryUri: publicLibraryUri,
        definition: GridAssetPackDefinition(
          package: package.name,
          assets: block.assets,
        ),
      ),
    );
  }

  final _ = GridAssetRegistry(<GridAssetPackDefinition>[
    for (final package in resolved) package.definition,
  ]);
  return List<ResolvedGridAssetPack>.unmodifiable(resolved);
}

/// Renders a Flutter-registrant-style library from [packages].
String renderStationAssetRegistryLibrary(
  Iterable<ResolvedGridAssetPack> packages,
) {
  final ordered = <ResolvedGridAssetPack>[...packages]
    ..sort((a, b) => a.name.compareTo(b.name));
  for (final package in ordered) {
    if (package.definition.package != package.name) {
      throw StationAssetRegistryException(
        'resolved package "${package.name}" contributes definition '
        '"${package.definition.package}"',
      );
    }
  }
  final _ = GridAssetRegistry(<GridAssetPackDefinition>[
    for (final package in ordered) package.definition,
  ]);

  final buffer = StringBuffer()
    ..writeln('// $kStationAssetRegistryGeneratedMarker — do not edit.')
    ..writeln(
      '// Sources: .dart_tool/package_config.json, pubspec.lock, and each',
    )
    ..writeln('// participating package\'s top-level `grid:` block.')
    ..writeln(
      '// Regenerate: dart run tool/generate_station_asset_registry.dart',
    )
    ..writeln()
    ..writeln('// Transitive imports are intentional: this is resolved output.')
    ..writeln('// ignore_for_file: depend_on_referenced_packages')
    ..writeln()
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:grid_sdk/grid_sdk.dart';");
  for (final package in ordered) {
    buffer.writeln(
      "import '${package.publicLibraryUri}' as ${_packAlias(package.name)};",
    );
  }
  buffer
    ..writeln()
    ..writeln('/// The complete asset registry generated for this station.')
    ..writeln('abstract final class GeneratedGridAssetRegistrant {')
    ..writeln('  /// Every pack in the resolved station closure.')
    ..writeln('  ///')
    ..writeln('  /// Built, not `const`: the SDK factory validates duplicate')
    ..writeln(
      '  /// logical and artifact identity before exposing the registry.',
    )
    ..writeln('  static final GridAssetRegistry registry = GridAssetRegistry(')
    ..writeln('    <GridAssetPackDefinition>[');
  for (final package in ordered) {
    buffer.writeln(
      '      ${_packAlias(package.name)}.GridAssetsPack.definition,',
    );
  }
  buffer
    ..writeln('    ],')
    ..writeln('  );')
    ..writeln('}');
  return DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  ).format(buffer.toString(), uri: kGeneratedStationAssetRegistryPath);
}

String _packAlias(String packageName) => '${packageName}_grid_asset_pack';

/// Generates or checks one station-local Dart registrant.
///
/// Discovery, parsing, validation, and rendering all finish before [outputPath]
/// is compared or written.
int runStationAssetRegistryGenerator({
  required String stationRoot,
  String outputPath = kGeneratedStationAssetRegistryPath,
  bool check = false,
  StringSink? out,
}) {
  final sink = out ?? stdout;
  final packages = resolveStationGridAssetPacks(stationRoot: stationRoot);
  final source = renderStationAssetRegistryLibrary(packages);
  final output = File(
    p.isAbsolute(outputPath) ? outputPath : p.join(stationRoot, outputPath),
  );
  final assetCount = packages.fold<int>(
    0,
    (count, package) => count + package.assets.length,
  );
  final report = '${packages.length} packs, $assetCount assets';

  if (check) {
    if (!output.existsSync() || output.readAsStringSync() != source) {
      sink.writeln(
        'STALE ${output.path} — run '
        '`dart run tool/generate_station_asset_registry.dart`',
      );
      sink.writeln('station assets: $report');
      return 1;
    }
    sink.writeln('station assets: $report');
    return 0;
  }

  output.parent.createSync(recursive: true);
  output.writeAsStringSync(source);
  sink.writeln('station assets: wrote ${output.path} — $report');
  return 0;
}

PackageConfig _parsePackageConfig(File file) {
  try {
    return PackageConfig.parseString(file.readAsStringSync(), file.uri);
  } on Object catch (error) {
    throw StationAssetRegistryException(
      '${file.path}: invalid package config: $error',
    );
  }
}

YamlMap _yamlMap(File file, String label) =>
    _parseYamlMap(file.readAsStringSync(), file.path, label);

YamlMap _parseYamlMap(String source, String path, String label) {
  try {
    final value = loadYaml(source);
    if (value is YamlMap) return value;
    throw StationAssetRegistryException('$path: $label must be a YAML map');
  } on StationAssetRegistryException {
    rethrow;
  } on Object catch (error) {
    throw StationAssetRegistryException('$path: invalid $label: $error');
  }
}
